<%!
    import onlinejudge_template.generator.cplusplus as cplusplus
    import onlinejudge_template.generator.about as about
%><%
    data['config']['indent'] = '\t'
    data['config']['scanner'] = 'cin'
    data['config']['printer'] = 'cout'
%>#include "template.hpp"

// #include <atcoder/all>
// using namespace atcoder;

// generated by ${about.title} ${about.version} (${about.url})
${cplusplus.declare_constants(data)}
int main(){
    
}